# Use an official Node.js image as the base
FROM node:14

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install dependencies
RUN npm install -g http-server

# Expose port 8080
EXPOSE 8080

# Run the application
CMD ["http-server", "-p", "8080"]